FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV THEME_DIR=/app/prod/shared_data/src/main/res/drawable-xxhdpi
ENV COLORS_XML_PATH=/app/prod/shared_data/src/main/theme/values/colors.xml

COPY . /app
EXPOSE 8000
CMD ["python3", "main.py"]
