import asyncio
import io
import re
from fastapi import FastAPI, File, Form, UploadFile, BackgroundTasks
from fastapi.responses import FileResponse
import os
import aiofiles
from typing import Optional, Union, Dict, Iterable, Tuple
import logging
import xml.etree.ElementTree as ET
from pathlib import Path
from PIL import Image, ImageDraw
from fastapi.middleware.cors import CORSMiddleware


app = FastAPI()
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # 모든 도메인 허용용
    allow_credentials=True,
    allow_methods=["*"],  # 모든 HTTP 메소드 허용
    allow_headers=["*"],  # 모든 HTTP 헤더 허용
)

BASE_DIR = Path(__file__).resolve().parent
ANDROID_PROJECT_ROOT_ENV = os.environ.get("ANDROID_PROJECT_ROOT")


def resolve_android_project_root() -> Path:
    candidates = []
    if ANDROID_PROJECT_ROOT_ENV:
        candidates.append(Path(ANDROID_PROJECT_ROOT_ENV))
    candidates.append(BASE_DIR / "kakao_theme_android")

    for path in candidates:
        if path.exists():
            return path

    searched = ", ".join(str(path) for path in candidates)
    raise FileNotFoundError(
        "안드로이드 프로젝트 경로를 찾을 수 없습니다. ANDROID_PROJECT_ROOT 환경 변수를 확인하세요. "
        f"탐색 경로: {searched}"
    )


ANDROID_PROJECT_ROOT = resolve_android_project_root()
ANDROID_PROJECT_ROOT_STR = str(ANDROID_PROJECT_ROOT)
DEFAULT_GRADLE_USER_HOME = os.environ.get("GRADLE_USER_HOME") or str(
    ANDROID_PROJECT_ROOT / ".gradle"
)
os.makedirs(DEFAULT_GRADLE_USER_HOME, exist_ok=True)

GRADLE_FILE_ENV = os.environ.get("ANDROID_GRADLE_FILE")
GRADLE_FILE_CANDIDATES = [
    Path(GRADLE_FILE_ENV) if GRADLE_FILE_ENV else None,
    ANDROID_PROJECT_ROOT / "build.gradle",
]

COMMON_ANDROID_SDK_PATHS = [
    Path.home() / "Library/Android/sdk",
    Path.home() / "Android/Sdk",
]


mipmap_dir = ANDROID_PROJECT_ROOT / "src" / "main"
theme_dir = ANDROID_PROJECT_ROOT / "src" / "main" / "theme" / "drawable-xxhdpi"
colors_xml_path = ANDROID_PROJECT_ROOT / "src" / "main" / "theme" / "values" / "colors.xml"
strings_xml_path = ANDROID_PROJECT_ROOT / "src" / "main" / "theme" / "values" / "strings.xml"
strings_ja_xml_path = (
    ANDROID_PROJECT_ROOT / "src" / "main" / "theme" / "values-ja" / "strings.xml"
)
strings_ko_xml_path = (
    ANDROID_PROJECT_ROOT / "src" / "main" / "theme" / "values-ko" / "strings.xml"
)

LAUNCHER_ICON_FILENAME = "commonIcoTheme.png"
ICON_SIZE_PATHS = {
    72: mipmap_dir / "res" / "mipmap-hdpi" / "ic_launcher_background.png",
    48: mipmap_dir / "res" / "mipmap-mdpi" / "ic_launcher_background.png",
    96: mipmap_dir / "res" / "mipmap-xhdpi" / "ic_launcher_background.png",
    144: mipmap_dir / "res" / "mipmap-xxhdpi" / "ic_launcher_background.png",
    192: mipmap_dir / "res" / "mipmap-xxxhdpi" / "ic_launcher_background.png",
    512: mipmap_dir / "ic_launcher-web.png",
}
LAUNCHER_ICON_OUTPUTS = {size: str(path) for size, path in ICON_SIZE_PATHS.items()}


def resolve_gradle_file_path() -> Path:
    for path in GRADLE_FILE_CANDIDATES:
        if path and path.exists():
            return path

    searched = ", ".join(str(path) for path in GRADLE_FILE_CANDIDATES if path)
    raise FileNotFoundError(
        "build.gradle 파일을 찾을 수 없습니다. ANDROID_GRADLE_FILE 환경 변수를 확인하세요. "
        f"탐색 경로: {searched}"
    )


def _format_local_properties_path(path: Path) -> str:
    value = str(path)
    value = value.replace("\\", "\\\\")
    value = value.replace(":", "\\:")
    value = value.replace(" ", "\\ ")
    return value


def _parse_sdk_dir_from_local_properties(local_properties_path: Path) -> Optional[Path]:
    if not local_properties_path.exists():
        return None

    with open(local_properties_path, "r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if line.startswith("sdk.dir="):
                raw_value = line.split("=", 1)[1]
                raw_value = raw_value.replace("\\ ", " ")
                raw_value = raw_value.replace("\\:", ":")
                raw_value = raw_value.replace("\\\\", "\\")
                return Path(raw_value).expanduser()
    return None


def _write_sdk_dir_to_local_properties(
    local_properties_path: Path, sdk_path: Path
) -> None:
    sdk_dir_line = f"sdk.dir={_format_local_properties_path(sdk_path)}\n"

    if local_properties_path.exists():
        with open(local_properties_path, "r", encoding="utf-8") as file:
            lines = file.readlines()
        updated = False
        for index, line in enumerate(lines):
            if line.startswith("sdk.dir="):
                lines[index] = sdk_dir_line
                updated = True
                break
        if not updated:
            lines.append(sdk_dir_line)
    else:
        lines = [
            "## Generated by backend to keep Gradle SDK path in sync\n",
            sdk_dir_line,
        ]

    with open(local_properties_path, "w", encoding="utf-8") as file:
        file.writelines(lines)


def ensure_android_sdk_path() -> Path:
    local_properties_path = ANDROID_PROJECT_ROOT / "local.properties"

    env_candidates = [
        os.environ.get("ANDROID_SDK_ROOT"),
        os.environ.get("ANDROID_HOME"),
    ]

    for candidate in env_candidates:
        if not candidate:
            continue
        sdk_path = Path(candidate).expanduser()
        if sdk_path.exists():
            _write_sdk_dir_to_local_properties(local_properties_path, sdk_path)
            return sdk_path

    existing_path = _parse_sdk_dir_from_local_properties(local_properties_path)
    if existing_path and existing_path.exists():
        return existing_path

    for candidate_path in COMMON_ANDROID_SDK_PATHS:
        if candidate_path.exists():
            _write_sdk_dir_to_local_properties(local_properties_path, candidate_path)
            return candidate_path

    raise FileNotFoundError(
        "Android SDK 경로를 찾을 수 없습니다. ANDROID_SDK_ROOT 또는 ANDROID_HOME 환경 변수를 설정하거나 "
        f"{local_properties_path} 파일의 sdk.dir 값을 유효한 경로로 업데이트하세요."
    )


@app.get("/test")
async def test():
    return "Success from android theme"


@app.post("/upload")
async def create_theme(
    background_tasks: BackgroundTasks,
    themeName: Optional[str] = Form(None),
    themeId: Optional[str] = Form(None),
    kakaoIcon: Optional[UploadFile] = File(None),
    tabsBgColor: Optional[str] = Form(None),
    tabsBg: Optional[UploadFile] = File(None),
    tabsFrends: Optional[UploadFile] = File(None),
    tabsFrendsSelected: Optional[UploadFile] = File(None),
    tabsChats: Optional[UploadFile] = File(None),
    tabsChatsSelected: Optional[UploadFile] = File(None),
    tabsOpenChats: Optional[UploadFile] = File(None),
    tabsOpenChatsSelected: Optional[UploadFile] = File(None),
    tabsNow: Optional[UploadFile] = File(None),
    tabsNowSelected: Optional[UploadFile] = File(None),
    tabsShopping: Optional[UploadFile] = File(None),
    tabsShoppingSelected: Optional[UploadFile] = File(None),
    tabsMore: Optional[UploadFile] = File(None),
    tabsMoreSelected: Optional[UploadFile] = File(None),
    mainBackgroundColor: Optional[str] = Form(None),
    mainBg: Optional[UploadFile] = File(None),
    headerColor: Optional[str] = Form(None),
    nameColor: Optional[str] = Form(None),
    namePressedColor: Optional[str] = Form(None),
    descriptionColor: Optional[str] = Form(None),
    descriptionPressedColor: Optional[str] = Form(None),
    paragraphColor: Optional[str] = Form(None),
    paragraphPressedColor: Optional[str] = Form(None),
    listBgColor: Optional[str] = Form(None),
    listBgPressedColor: Optional[str] = Form(None),
    listBgOpacity: Optional[float] = Form(None),
    listBgPressedOpacity: Optional[float] = Form(None),
    borderColor: Optional[str] = Form(None),
    borderOpacity: Optional[float] = Form(None),
    sectionColor: Optional[str] = Form(None),
    sectionOpacity: Optional[float] = Form(None),
    subBgColor: Optional[str] = Form(None),
    bottomBannerBgColor: Optional[str] = Form(None),
    serviceBtnColor: Optional[str] = Form(None),
    findFriendButton: Optional[UploadFile] = File(None),
    defaultProfile: Optional[UploadFile] = File(None),
    chatRoomBgColor: Optional[str] = Form(None),
    chatRoomBg: Optional[UploadFile] = File(None),
    inputBarBgColor: Optional[str] = Form(None),
    sendBgColor: Optional[str] = Form(None),
    sendBgPressedColor: Optional[str] = Form(None),
    sendIconColor: Optional[str] = Form(None),
    sendIconPressedColor: Optional[str] = Form(None),
    menuButtonColor: Optional[str] = Form(None),
    menuButtonPressedColor: Optional[str] = Form(None),
    bubbleSend1: Optional[UploadFile] = File(None),
    bubbleSend1Selected: Optional[UploadFile] = File(None),
    sendEdgeinsets1: Optional[str] = Form(None),
    bubbleSend2: Optional[UploadFile] = File(None),
    bubbleSend2Selected: Optional[UploadFile] = File(None),
    sendEdgeinsets2: Optional[str] = Form(None),
    textColor: Optional[str] = Form(None),
    textSelectedColor: Optional[str] = Form(None),
    unReadColor: Optional[str] = Form(None),
    bubbleReceive1: Optional[UploadFile] = File(None),
    bubbleReceive1Selected: Optional[UploadFile] = File(None),
    receiveEdgeinsets1: Optional[str] = Form(None),
    bubbleReceive2: Optional[UploadFile] = File(None),
    bubbleReceive2Selected: Optional[UploadFile] = File(None),
    receiveEdgeinsets2: Optional[str] = Form(None),
    receiveTextColor: Optional[str] = Form(None),
    receiveTextSelectedColor: Optional[str] = Form(None),
    receiveUnReadColor: Optional[str] = Form(None),
    passcodeBgColor: Optional[str] = Form(None),
    passcodeBg: Optional[UploadFile] = File(None),
    passcodeTitleColor: Optional[str] = Form(None),
    passcodeImage1: Optional[UploadFile] = File(None),
    passcodeImage2: Optional[UploadFile] = File(None),
    passcodeImage3: Optional[UploadFile] = File(None),
    passcodeImage4: Optional[UploadFile] = File(None),
    passcodeImage1Selected: Optional[UploadFile] = File(None),
    passcodeImage2Selected: Optional[UploadFile] = File(None),
    passcodeImage3Selected: Optional[UploadFile] = File(None),
    passcodeImage4Selected: Optional[UploadFile] = File(None),
    keyPadBgColor: Optional[str] = Form(None),
    keyPadTextColor: Optional[str] = Form(None),
    keyPadPressedImage: Optional[UploadFile] = Form(None),
    alertMessageBgColor: Optional[str] = Form(None),
    alertMessageNameColor: Optional[str] = Form(None),
    alertMessageTextColor: Optional[str] = Form(None),
    alertShareBgColor: Optional[str] = Form(None),
    alertShareNameColor: Optional[str] = Form(None),
    alertShareTextColor: Optional[str] = Form(None),
):
    # 테마 디렉토리 생성
    theme_dir.mkdir(parents=True, exist_ok=True)

    await update_version_in_gradle()

    open_chat_icon = tabsOpenChats or tabsNow
    open_chat_icon_selected = tabsOpenChatsSelected or tabsNowSelected

    image_tasks = [
        (kakaoIcon, LAUNCHER_ICON_FILENAME),
        (tabsBg, "theme_background_image.png"),
        (tabsFrends, "theme_maintab_ico_friends_image.png"),
        (tabsFrendsSelected, "theme_maintab_ico_friends_focused_image.png"),
        (tabsChats, "theme_maintab_ico_chats_image.png"),
        (tabsChatsSelected, "theme_maintab_ico_chats_focused_image.png"),
        (open_chat_icon, "theme_maintab_ico_openchat_image.png"),
        (
            open_chat_icon_selected,
            "theme_maintab_ico_openchat_focused_image.png",
        ),
        (tabsNow, "theme_maintab_ico_now_image.png"),
        (tabsNowSelected, "theme_maintab_ico_now_focused_image.png"),
        (tabsShopping, "theme_maintab_ico_shopping_image.png"),
        (tabsShoppingSelected, "theme_maintab_ico_shopping_focused_image.png"),
        (tabsMore, "theme_maintab_ico_more_image.png"),
        (tabsMoreSelected, "theme_maintab_ico_more_focused_image.png"),
        (mainBg, "theme_background_image.png"),
        (findFriendButton, "theme_find_add_friend_button_image.png"),
        (defaultProfile, "theme_profile_01_image.png"),
        (chatRoomBg, "theme_chatroom_background_image.png"),
        (bubbleSend1, "theme_chatroom_bubble_me_01_image.9.png"),
        (bubbleSend2, "theme_chatroom_bubble_me_02_image.9.png"),
        (bubbleReceive1, "theme_chatroom_bubble_you_01_image.9.png"),
        (bubbleReceive2, "theme_chatroom_bubble_you_02_image.9.png"),
        (passcodeBg, "theme_passcode_background_image.png"),
        (passcodeImage1, "theme_passcode_01_image.png"),
        (passcodeImage2, "theme_passcode_02_image.png"),
        (passcodeImage3, "theme_passcode_03_image.png"),
        (passcodeImage4, "theme_passcode_04_image.png"),
        (passcodeImage1Selected, "theme_passcode_01_checked_image.png"),
        (passcodeImage2Selected, "theme_passcode_02_checked_image.png"),
        (passcodeImage3Selected, "theme_passcode_03_checked_image.png"),
        (passcodeImage4Selected, "theme_passcode_04_checked_image.png"),
    ]

    nine_patch_locations = {
        "theme_chatroom_bubble_me_01_image.9.png": sendEdgeinsets1,
        "theme_chatroom_bubble_me_02_image.9.png": sendEdgeinsets2,
        "theme_chatroom_bubble_you_01_image.9.png": receiveEdgeinsets1,
        "theme_chatroom_bubble_you_02_image.9.png": receiveEdgeinsets2,
    }

    await persist_uploaded_images(image_tasks, nine_patch_locations)

    logger.info("theme file saved")

    for text_name in ("theme_title", "app_name"):
        update_text(text_name, themeName)

    color_map = {
        "theme_header_color": headerColor,
        "theme_section_title_color": sectionColor,
        "theme_title_color": nameColor,
        "theme_title_pressed_color": namePressedColor,
        "theme_paragraph_color": paragraphColor,
        "theme_paragraph_pressed_color": paragraphPressedColor,
        "theme_description_color": descriptionColor,
        "theme_description_pressed_color": descriptionPressedColor,
        "theme_feature_primary_color": serviceBtnColor,
        "theme_feature_primary_pressed_color": serviceBtnColor,
        "theme_background_color": mainBackgroundColor,
        "theme_header_cell_color": mainBackgroundColor,
        "theme_chatroom_background_color": chatRoomBgColor,
        "theme_passcode_background_color": passcodeBgColor,
        "theme_body_cell_pressed_color": listBgPressedColor,
        "theme_body_secondary_cell_color": subBgColor,
        "theme_tab_bannerbadge_background_color": bottomBannerBgColor,
        "theme_direct_share_color": alertShareTextColor,
        "theme_direct_share_button_color": alertShareNameColor,
        "theme_direct_share_background_color": alertShareBgColor,
        "theme_notification_color": alertMessageTextColor,
        "theme_notification_background_color": alertMessageBgColor,
        "theme_notification_background_pressed_color": alertMessageBgColor,
        "theme_passcode_color": passcodeTitleColor,
        "theme_passcode_keypad_color": keyPadTextColor,
        "theme_passcode_keypad_pressed_color": keyPadTextColor,
        "theme_passcode_keypad_background_color": keyPadBgColor,
        "theme_passcode_pattern_line_color": keyPadTextColor,
        "theme_chatroom_bubble_me_color": textColor,
        "theme_chatroom_bubble_you_color": receiveTextColor,
        "theme_chatroom_unread_count_color": unReadColor,
        "theme_chatroom_input_bar_background_color": inputBarBgColor,
        "theme_chatroom_input_bar_send_button_color": sendBgColor,
        "theme_chatroom_input_bar_send_icon_color": sendIconColor,
        "theme_chatroom_input_bar_menu_icon_color": menuButtonColor,
    }

    for color_name, value in color_map.items():
        update_color(color_name, value)

    combined_color_map = {
        "theme_body_cell_border_color": (borderColor, borderOpacity),
        "theme_body_cell_color": (listBgColor, listBgOpacity),
        "theme_maintab_cell_color": (tabsBgColor, 1),
        "theme_passcode_keypad_pressed_background_color": (keyPadBgColor, 0.5),
    }

    for color_name, (color_value, opacity_value) in combined_color_map.items():
        update_color(color_name, combine_color_and_opacity(color_value, opacity_value))

    logger.info("update theme colors completed")

    apk_path = await build_apk()

    return FileResponse(apk_path, filename="custom_theme.apk")


def increment_version(version):
    major, minor, patch = map(int, version.split("."))
    patch += 1
    if patch == 1000:
        patch = 0
        minor += 1
        if minor == 1000:
            minor = 0
            major += 1
    return f"{major}.{minor}.{patch}"


async def update_version_in_gradle():
    gradle_file = resolve_gradle_file_path()
    async with aiofiles.open(gradle_file, "r") as file:
        content = await file.read()

    version_pattern = r'versionName\s+"(\d+\.\d+\.\d+)"'
    match = re.search(version_pattern, content)
    if match:
        current_version = match.group(1)
        new_version = increment_version(current_version)
        content = re.sub(version_pattern, f'versionName "{new_version}"', content)

        async with aiofiles.open(gradle_file, "w") as file:
            await file.write(content)

        logger.info(f"Version updated from {current_version} to {new_version} ({gradle_file})")
    else:
        logger.warning("Version not found in build.gradle")


async def persist_uploaded_images(
    image_tasks: Iterable[Tuple[Optional[UploadFile], str]],
    nine_patch_locations: Dict[str, Optional[str]],
) -> None:
    for image_file, filename in image_tasks:
        if image_file is None:
            continue

        content = await image_file.read()
        location = nine_patch_locations.get(filename)
        if location:
            content = create_nine_patch(content, location)

        if filename == LAUNCHER_ICON_FILENAME:
            create_mipmaps(content, LAUNCHER_ICON_OUTPUTS)
            continue

        file_path = theme_dir / filename
        file_path.parent.mkdir(parents=True, exist_ok=True)
        async with aiofiles.open(file_path, "wb") as out_file:
            await out_file.write(content)


def create_mipmaps(image_bytes, size_paths):
    original_image = Image.open(io.BytesIO(image_bytes))

    for size, path in size_paths.items():
        # Create and save background image
        resized_image = original_image.copy()
        resized_image.thumbnail((size, size))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        resized_image.save(path)
        logger.info(f"Saved background mipmap {size}x{size} to: {path}")

        # Create and save transparent foreground image
        foreground_path = path.replace("background", "foreground")
        transparent_image = Image.new('RGBA', (size, size), (0, 0, 0, 0))
        transparent_image.save(foreground_path)
        logger.info(f"Saved transparent foreground mipmap {size}x{size} to: {foreground_path}")


def update_text(text_name, new_value):
    xml_paths = [strings_xml_path, strings_ja_xml_path, strings_ko_xml_path]

    for path in xml_paths:
        tree = ET.parse(path)
        root = tree.getroot()

        for color_element in root.findall(".//string[@name='{}']".format(text_name)):
            if new_value is not None:
                color_element.text = str(new_value)

        tree.write(path, encoding="utf-8", xml_declaration=True)


def update_color(color_name, new_value):
    # XML 파일 파싱
    tree = ET.parse(colors_xml_path)
    root = tree.getroot()

    # 'name' 속성으로 색상 요소 찾기
    for color_element in root.findall(".//color[@name='{}']".format(color_name)):
        # 새 값으로 업데이트
        if new_value is not None:
            color_element.text = str(new_value)

    # 변경사항 저장
    tree.write(colors_xml_path, encoding="utf-8", xml_declaration=True)


async def build_apk():
    project_root = ANDROID_PROJECT_ROOT
    gradlew_path = project_root / "gradlew"

    if not gradlew_path.exists():
        raise FileNotFoundError(
            f"gradlew 스크립트를 찾을 수 없습니다: {gradlew_path}. "
            "ANDROID_PROJECT_ROOT 설정을 확인하세요."
        )

    sdk_path = ensure_android_sdk_path()
    logger.info(f"Android SDK path resolved to: {sdk_path}")

    env = os.environ.copy()
    env.setdefault("GRADLE_USER_HOME", DEFAULT_GRADLE_USER_HOME)

    try:
        process = await asyncio.create_subprocess_exec(
            str(gradlew_path),
            "assembleDebug",
            cwd=str(project_root),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=env,
        )

        async def log_stream(stream, log_func):
            while True:
                line = await stream.readline()
                if not line:
                    break
                log_func(line.decode().strip())

        await asyncio.gather(
            log_stream(process.stdout, logger.info),
            log_stream(process.stderr, logger.error),
        )

        await process.wait()

        if process.returncode == 0:
            apk_path = project_root / "build/outputs/apk/debug/ONO-theme.apk"
            if not apk_path.exists():
                raise FileNotFoundError(
                    f"APK 결과물을 찾을 수 없습니다: {apk_path}."
                )
            logger.info("Build successful")
            return str(apk_path)
        else:
            logger.error("Build failed")
            raise Exception("Build process failed")

    except Exception as e:
        logger.exception("An error occurred during the build process")
        raise Exception(f"Build error: {str(e)}")


def opacity_to_hex(opacity: Union[float, int, None] = None) -> str:
    if opacity is None:
        opacity_float = 1.0
    else:
        try:
            opacity_float = float(opacity)
        except ValueError:
            raise ValueError("Opacity must be a number", opacity)

        if not 0 <= opacity_float <= 1:
            raise ValueError("Opacity must be between 0 and 1", opacity)

    hex_value = int(opacity_float * 255)
    return f"{hex_value:02X}"


def combine_color_and_opacity(
    color: Optional[str], opacity: Union[float, int, None]
) -> Optional[str]:
    if color is None:
        return None
    hex_color = color.lstrip("#")
    return "#" + opacity_to_hex(opacity) + hex_color


def create_nine_patch(imageObj, location):
    stretch_width, stretch_height, padding_width, padding_height = map(
        lambda x: int(x.rstrip("px")), location.split()
    )

    # Open the image
    img = Image.open(io.BytesIO(imageObj))

    # Calculate the start and end points for stretch and padding areas
    left_start = (img.width - stretch_width) // 2
    left_end = left_start + stretch_width
    top_start = (img.height - stretch_height) // 2
    top_end = top_start + stretch_height

    right_start = (img.height - padding_height) // 2
    right_end = right_start + padding_height
    bottom_start = (img.width - padding_width) // 2
    bottom_end = bottom_start + padding_width

    # Create a new image with a 1-pixel border
    nine_patch = Image.new("RGBA", (img.width + 2, img.height + 2), (0, 0, 0, 0))

    # Paste the original image into the center
    nine_patch.paste(img, (1, 1))

    # Create a drawing object
    draw = ImageDraw.Draw(nine_patch)

    # Draw the stretchable areas (left and top)
    draw.line([(0, 0), (left_start, 0)], fill=(0, 0, 0, 0))
    draw.line([(left_start, 0), (left_end, 0)], fill="black")
    draw.line([(left_end, 0), (img.width + 1, 0)], fill=(0, 0, 0, 0))

    draw.line([(0, 0), (0, top_start)], fill=(0, 0, 0, 0))
    draw.line([(0, top_start), (0, top_end)], fill="black")
    draw.line([(0, top_end), (0, img.height + 1)], fill=(0, 0, 0, 0))

    # Draw the padding box (right and bottom)
    draw.line([(img.width + 1, 0), (img.width + 1, right_start)], fill=(0, 0, 0, 0))
    draw.line([(img.width + 1, right_start), (img.width + 1, right_end)], fill="black")
    draw.line(
        [(img.width + 1, right_end), (img.width + 1, img.height + 1)], fill=(0, 0, 0, 0)
    )

    draw.line([(0, img.height + 1), (bottom_start, img.height + 1)], fill=(0, 0, 0, 0))
    draw.line(
        [(bottom_start, img.height + 1), (bottom_end, img.height + 1)], fill="black"
    )
    draw.line(
        [(bottom_end, img.height + 1), (img.width + 1, img.height + 1)],
        fill=(0, 0, 0, 0),
    )

    # Save the nine-patch image to a bytes buffer
    buffer = io.BytesIO()
    nine_patch.save(buffer, format="PNG")
    return buffer.getvalue()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
